### ISSUE TITLE
Model Edit Page

### ISSUE THREAD

**Issue by 12rcu** [KeepMeAlive3D/KeepMeAlive3D#10]
Create a page where web users can add, modify and delete tags of a uploaded model

- [x] Import of file
- [ ] Tree view of all elements, selectable, highlighted in view
- [ ] View: selectable elements
- [ ] Open dialog to add mqtt topic, data format
- [ ] Overview of what has been selected so far
- [ ] Input to submit to backend

**Comment by olfarmer** [comment]
Clarify the best way to solve this. Options: proceed implementing the UI or use the custom data which can be set in Blender.

**Comment by olfarmer** [comment]
The scope of this issue changed as the data will be annotated in external tools like Blender. Hence, an edit page is not required.
